### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by bertRC** [bertRC/taxi#3]
Здравствуйте!
Сделал почти как в видео про Maven Plugins & Travis CI, с учетом того что проект уже был создан и коммиты были в ветке master.

Вопросы:
1. По инструкции в документе Ссылки на все материалы - "Рабочий конфиг для Maven’а и Travis CI берите из проекта KFC". Однако в данном файле .travis.yml отсутствует скрипт для codecov.io как на видео. Он всё-таки нужен или пока нет?
2. Из видео не вполне понятно как подавать на проверку ДЗ. Не через Issues? Через Pull Request? Кнопку Merge в конце нажимаю я или вы?

**Comment by coursar** [comment]
1. Нет, пока codecov не нужен (мы пройдём на следующей лекции)
2. Пока через issue, pull-request'ы, merge и т.д. мы ещё не проходили
